### PR TITLE
Navbar Redesign

### PR DESCRIPTION
**Pull request by InBlue**
I completely redesigned the navigation bar. Any feedback is appreciated as always. This also includes some changes to the homepage style sheet for responsiveness as there were a few issues I noticed.

### CODE REVIEW

**Review by melmsie — CHANGES_REQUESTED** [review]
The navbar is fine looking more minimal than before, however I think it looks a bit out of place with a different font than the rest of the website. Also, a few pages (/loot, /terms) look bad with the new navbar due to weird spacing, but I'm assuming you're just kinda going page to page and redesigning anyway at this point so that may not need addressed here.

Also, the mobile view has some weird spacing above the nav items 
image

**Comment by InBlue** [comment]
I have the user information when logged in above the links - I might move it to the bottom so that the awkward spacing isn't there. Which font were you talking about is different? I think I am using Inter for the links and Montserrat for the text at the top.

**Comment by melmsie** [comment]
I think it's the Inter that looks off then maybe, I know we used Montserrat before which overall looks more bold than this. I'm not quite sure what it needs, it just feels a bit less cohesive with the site as is.

As for the space, I haven't tried logging in. I'll do that and check back in, but something changed for when they're not logged in would probably be good yeah

**Comment by melmsie** [comment]
Ok so mobile while logged in looks great. Desktop is a bit funky, looks like the spacing might be off?

image

**Comment by InBlue** [comment]
> 
> 
> Ok so mobile while logged in looks great. Desktop is a bit funky, looks like the spacing might be off?
> 
> image

The logout is meant to be centered but I can left-align it. I didn't check responsiveness on the dropdown - I will fix.

**Pull request merged**
