### PR TITLE
Homepage redesign & update

### PR DESCRIPTION
**Pull request by InBlue**
I am going to start redesigning the homepage in line with the mock-up that I created.
This PR will also include the conversion of the old homepage into a new functional component.

**I removed the refs from the page and also the anchor checking when the component is ready - If this is needed let me know.**
**I also am building this off of the previous and currently unmerged _restructure_ branch**

### CODE REVIEW

**Comment by melmsie** [comment]
Looks good for the most part! Only issue I still see, is that the bottom picture in the features section is squished.

Also, before it goes to production it'll either need google ads added back (you have the code pushing it, but not the actual ads on the page), or to add the [new nitropay ad stuff](https://trello.com/c/5Wn1CSfT/16-adsense-nitropay) which we want to switch to anyway. Not sure if you want that included in THIS commit since this is just the homepage, and the ads will need to be site-wide.

**Review by melmsie — CHANGES_REQUESTED** [review]
See above comment ^

**Comment by InBlue** [comment]
> 
> 
> See above comment ^

I was going to change the normal text fonts to Inter - However if you do not want this I can stick with Lato. Could I see a screenshot of the image being squashed - They look normal to me.

**Comment by melmsie** [comment]
image

If you're changing everything to Inter, that's fine. Just looks funky with both of them.

**Comment by InBlue** [comment]
> 
> 
> image
> 
> If you're changing everything to Inter, that's fine. Just looks funky with both of them.

I can't reproduce that image with Firefox responsive design tool. Also, confirming you are using the latest version of the branch as the background seems to be `fixed` when it should be `absolute` or something else is causing the circles to go down the page.

**Pull request merged**
