### PR TITLE
Finished page redesigns with some bug fixes.

### PR DESCRIPTION
**Pull request by InBlue**
This PR includes a few changes on some of the pages.
Including 
- Fixed homepage image sizing.
- Changed the sliding categories on the commands page to a dropdown menu.
- Changed the FAQ page to be the same design as the commands page but with different content.
  - If you rather this have a different design for the website redesign let me know and I will mock one up.

### CODE REVIEW

**Comment by InBlue** [comment]
Sorry about the last commit - I was working on the blog page redesign and need to sleep so I pushed my changes just in case of anything happening.
**Please don't merge this branch until I update the blog page unless you rather it be on master and I update the blog page tomorrow with a new PR**

**Comment by InBlue** [comment]
This latest commit (5dda43) includes a lot of work done on the store page, however, it is not done. I have updated Axios in this commit - I am not sure if it was used anywhere but it is now on `^0.21.0`. I am also using a new dependency (react-paypal-button-v2) for the PayPal button. This dependency solved a lot of headaches and challenges with moving the store page to a functional component.

Some of the content of the page is still missing - mainly a header with some extra information and the easter eggs.

**Known bugs:**
- The input fields will allow numbers outside the range to be enter (Should be fixed soon)
- No discount shown to the user
- The PayPal buttons will not show up if the purchase is a gift (Even after the user id is entered and valid.)

**Comment by InBlue** [comment]
I have to add a few checks to the store page before it should be good for master. It currently doesn't block users in restricted countries to name the most important feature.

**Comment by InBlue** [comment]
Everything should be operational in this PR now.

**Comment by InBlue** [comment]
The responsive design is really weird. I am not sure why the spacing is so messed up - large margins used everywhere on smaller devices to move divs around. I might look into it later, it works for now.

**Comment by InBlue** [comment]
Everything on this PR has been checked. I may have missed something so it is best to check again before a merge. Though if everything is good it should be able to be merged.

**Review by melmsie — APPROVED** [review]

**Pull request merged**
